const fallback={hero_eyebrow:'DIGITAL MARKETING SPECIALIST · BANGLADESH',hero_title:'Turning attention into measurable growth.',hero_copy:'I help brands grow through performance marketing, Meta Ads, e-commerce strategy and data-driven optimization.',hero_primary_label:'Explore My Work',hero_primary_url:'#work',hero_secondary_label:'Start a Conversation',hero_secondary_url:'#contact',about_name:'Omar Faruk.',about_lead:'A Digital Marketing Specialist focused on helping brands grow through paid media, e-commerce marketing and performance-driven strategy.',about_body:'I work across Meta advertising, creative strategy, retargeting, analytics and conversion tracking. My goal is simple: understand the business, identify the bottleneck, test intelligently and scale what works.',about_role:'Digital Marketing Specialist',about_specialties:'Meta Ads · Performance Marketing · E-commerce',contact_heading:'Have a growth challenge?',contact_copy:"Tell me what you're working on. Let's see where performance marketing can make a difference.",footer_tagline:'Digital Marketing · Performance · Growth'};
const clean=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function set(id,val){const el=document.getElementById(id);if(el&&val!=null)el.textContent=val;}
function setLink(id,label,url){const el=document.getElementById(id);if(!el)return;el.textContent='';el.append(label+' ');const span=document.createElement('span');span.textContent='↗';el.append(span);el.href=url||'#';}
async function load(){
 let data=fallback,services=[],projects=[],insights=[],testimonials=[];
 try{const sb=supabase.createClient(window.SUPABASE_URL,window.SUPABASE_ANON_KEY); const r=await Promise.all([sb.from('site_content').select('*').eq('id',1).single(),sb.from('services').select('*').order('sort_order'),sb.from('projects').select('*').order('sort_order'),sb.from('insights').select('*').eq('published',true).order('sort_order'),sb.from('testimonials').select('*').eq('published',true).order('sort_order')]); data={...fallback,...(r[0].data||{})};services=r[1].data||[];projects=r[2].data||[];insights=r[3].data||[];testimonials=r[4].data||[]; if(!services.length)throw 0;}catch(e){services=[{number:'01',title:'Meta Ads',description:'Campaign strategy, audience research, creative testing, retargeting and scalable account structures.'},{number:'02',title:'E-commerce Growth',description:'Full-funnel acquisition strategies designed around product, offer, creative and conversion data.'},{number:'03',title:'Tracking & Analytics',description:'GTM, GA4, Meta Pixel, Conversion API and event architecture for cleaner decision-making.'},{number:'04',title:'Creative Strategy',description:'Scroll-stopping concepts, content angles and testing frameworks that turn creative into a performance lever.'}];}
 set('heroEyebrow',data.hero_eyebrow);set('heroTitle',data.hero_title);set('heroCopy',data.hero_copy);setLink('heroPrimary',data.hero_primary_label,data.hero_primary_url);setLink('heroSecondary',data.hero_secondary_label,data.hero_secondary_url);set('aboutName',data.about_name);set('aboutLead',data.about_lead);set('aboutBody',data.about_body);set('aboutRole',data.about_role);set('aboutSpecialties',data.about_specialties);set('contactHeading',data.contact_heading);set('contactCopy',data.contact_copy);set('footerTagline',data.footer_tagline);
 const avatar=document.getElementById('avatar'); if(avatar){ if(data.profile_image_url){ avatar.innerHTML=`<img src="${clean(data.profile_image_url)}" alt="${clean(data.about_name||'Omar Faruk')}">`; } else { avatar.textContent='OF'; }}document.title=data.seo_title||'Omar Faruk — Digital Marketing Specialist';document.querySelector('meta[name="description"]').setAttribute('content',data.seo_description||'');
 const sg=document.getElementById('servicesGrid');sg.innerHTML=services.map((x,i)=>`<article><b>${clean(x.number||String(i+1).padStart(2,'0'))}</b><h3>${clean(x.title)}</h3><p>${clean(x.description)}</p><a href="${clean(x.cta_url||'#contact')}">${clean(x.cta_label||'Explore ↗')}</a></article>`).join('');
 const pg=document.getElementById('projectsGrid');pg.innerHTML=projects.map((x,i)=>`<article class="case ${x.featured?'featured':''}"><div class="case-visual ${['gradient-a','gradient-b','gradient-c','gradient-d'][i%4]}" ${x.image_url?`style="background-image:url('${clean(x.image_url)}');background-size:cover;background-position:center"`:''}><span>${clean(x.category)}</span><strong>${clean(x.title)}</strong></div><div class="case-info"><div><small>${clean(x.category)}</small><h3>${clean(x.description)}</h3></div><a href="${clean(x.cta_url||'#contact')}">${clean(x.cta_label||'View Work ↗')}</a></div></article>`).join('');
 const ig=document.getElementById('insightsGrid');ig.innerHTML=insights.map(x=>`<article><small>${clean(x.category)}</small><h3>${clean(x.title)}</h3><p>${clean(x.excerpt)}</p><a href="${clean(x.url||'#contact')}">Read article ↗</a></article>`).join('');
 const tg=document.getElementById('testimonialsGrid');tg.innerHTML=testimonials.length?testimonials.map(x=>`<article><small>${clean(x.company||x.role)}</small><h3>“${clean(x.quote)}”</h3><p>${clean(x.name)}${x.role?' · '+clean(x.role):''}</p></article>`).join(''):'<article><small>CLIENT FEEDBACK</small><h3>Testimonials can be added from the admin panel.</h3><p>Publish feedback when you are ready.</p></article>';
 const social=document.getElementById('socials'); social.innerHTML=[['LinkedIn',data.linkedin_url],['Facebook',data.facebook_url],['WhatsApp',data.whatsapp_url],['Email',data.email?'mailto:'+data.email:'']].filter(x=>x[1]).map(x=>`<a href="${clean(x[1])}" target="_blank" rel="noreferrer">${clean(x[0])} ↗</a>`).join('');
 document.getElementById('year').textContent=new Date().getFullYear();
}
load();
