const { createClient } = supabase;
const sb = createClient(window.SUPABASE_URL, window.SUPABASE_ANON_KEY);
const $ = s => document.querySelector(s);
const $$ = s => [...document.querySelectorAll(s)];
const toast = msg => { const t=$('#toast'); t.textContent=msg; t.style.display='block'; setTimeout(()=>t.style.display='none',2200); };
const esc = s => String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));

async function boot(){ const {data:{session}}=await sb.auth.getSession(); if(session) showApp(); else $('#loginView').classList.remove('hidden'); }
function showApp(){ $('#loginView').classList.add('hidden'); $('#app').classList.remove('hidden'); loadAll(); }
$('#loginForm').addEventListener('submit', async e=>{e.preventDefault(); $('#loginError').textContent=''; const {error}=await sb.auth.signInWithPassword({email:$('#email').value,password:$('#password').value}); if(error) $('#loginError').textContent=error.message; else showApp();});
$('#logout').onclick=async()=>{await sb.auth.signOut(); location.reload();};
$$('.nav button[data-tab]').forEach(b=>b.onclick=()=>{ $$('.nav button').forEach(x=>x.classList.remove('active')); b.classList.add('active'); $$('.panel').forEach(p=>p.classList.remove('active')); $('#'+b.dataset.tab).classList.add('active'); $('#pageTitle').textContent=b.textContent; });

async function loadAll(){ await Promise.all([loadHome(),loadCollection('services'),loadCollection('projects'),loadCollection('insights'),loadCollection('testimonials')]); }
async function loadHome(){ const {data,error}=await sb.from('site_content').select('*').eq('id',1).single(); if(error){$('#status').textContent=error.message;return;} fill($('#homeForm'),data); fill($('#settingsForm'),data); if(!$('#profileUpload')){ const wrap=document.createElement('div'); wrap.innerHTML='<label>Upload profile image</label><input id="profileUpload" type="file" accept="image/*"><div class="status">Uploading replaces the profile image URL when you save.</div>'; const target=$('#homeForm').querySelector('[name=profile_image_url]')?.parentElement; if(target) target.appendChild(wrap); $('#profileUpload').onchange=async()=>{try{const url=await uploadImage($('#profileUpload').files[0]); $('#homeForm').elements.profile_image_url.value=url; toast('Image uploaded');}catch(err){toast(err.message)}}; }}
function fill(form,data){ Object.entries(data||{}).forEach(([k,v])=>{ const el=form.elements[k]; if(el) el.value=v??''; }); }
async function saveForm(form){ const obj={}; [...form.elements].forEach(el=>{if(el.name) obj[el.name]=el.value}); obj.updated_at=new Date().toISOString(); const {error}=await sb.from('site_content').update(obj).eq('id',1); if(error) throw error; toast('Saved successfully'); }
$('#homeForm').onsubmit=async e=>{e.preventDefault();try{await saveForm(e.target)}catch(x){toast(x.message)}};
$('#settingsForm').onsubmit=async e=>{e.preventDefault();try{await saveForm(e.target)}catch(x){toast(x.message)}};

const schemas={services:{title:'Service',fields:[['number','Number'],['title','Title'],['description','Description','textarea'],['cta_label','Button label'],['cta_url','Button URL'],['sort_order','Order','number']]},projects:{title:'Project',fields:[['category','Category'],['title','Title'],['description','Description','textarea'],['services_used','Services / skills used','textarea'],['results','Results / metrics','textarea'],['image_url','Image URL'],['cta_label','Button label'],['cta_url','Button URL'],['sort_order','Order','number'],['featured','Featured','checkbox']]},insights:{title:'Insight',fields:[['category','Category'],['title','Title'],['excerpt','Excerpt','textarea'],['url','Article URL'],['sort_order','Order','number'],['published','Published','checkbox']]},testimonials:{title:'Testimonial',fields:[['name','Name'],['role','Role'],['company','Company'],['quote','Quote','textarea'],['avatar_url','Avatar URL'],['sort_order','Order','number'],['published','Published','checkbox']]}};
async function loadCollection(table){ const {data,error}=await sb.from(table).select('*').order('sort_order',{ascending:true}); if(error){toast(error.message);return;} $('#'+table+'List').innerHTML=''; data.forEach(row=>addListItem(table,row)); $('#count'+table[0].toUpperCase()+table.slice(1)).textContent=data.length; }
function addListItem(table,row){ const box=document.createElement('div'); box.className='item'; box.innerHTML=`<div><strong>${esc(row.title||row.name||'Untitled')}</strong><small>${esc(row.category||row.role||'')}</small></div><div><button class="btn" data-edit>Edit</button> <button class="btn danger" data-delete>Delete</button></div>`; box.querySelector('[data-edit]').onclick=()=>editRow(table,row); box.querySelector('[data-delete]').onclick=()=>deleteRow(table,row.id); $('#'+table+'List').appendChild(box); }
function editRow(table,row){ const s=schemas[table]; const imageFields=['image_url','avatar_url']; const html=s.fields.map(([k,label,type])=>{ const isImg=imageFields.includes(k); return `<div class="${['description','quote','services_used','results'].includes(k)?'full':''}"><label>${label}</label>${type==='textarea'?`<textarea name="${k}">${esc(row[k]||'')}</textarea>`:type==='checkbox'?`<input type="checkbox" name="${k}" ${row[k]?'checked':''}>`:type==='number'?`<input type="number" name="${k}" value="${row[k]??0}">`:`<input name="${k}" value="${esc(row[k]||'')}" ${isImg?'data-image-url':''}>${isImg?`<div style="margin-top:8px"><input type="file" accept="image/*" data-image-file="${k}"><small style="color:#9da6b2">Upload image or paste a URL above.</small></div>`:''}`}</div>`; }).join(''); const modal=document.createElement('div'); modal.style='position:fixed;inset:0;background:#000b;display:grid;place-items:center;padding:20px;z-index:10'; modal.innerHTML=`<div class="card" style="width:min(760px,100%);max-height:90vh;overflow:auto"><h2>${row.id?'Edit':'Add'} ${s.title}</h2><form class="grid">${html}</form><div class="row"><button class="btn" type="button" data-close>Cancel</button><button class="btn primary" type="button" data-save>Save</button></div></div>`; document.body.appendChild(modal); modal.querySelector('[data-close]').onclick=()=>modal.remove(); modal.querySelector('[data-save]').onclick=async()=>{const save=modal.querySelector('[data-save]'); save.disabled=true; try{const obj={}; [...modal.querySelector('form').elements].forEach(el=>{if(el.name)obj[el.name]=el.type==='checkbox'?el.checked:el.value}); for(const k of imageFields){const fileEl=modal.querySelector(`[data-image-file="${k}"]`); if(fileEl?.files?.[0]) obj[k]=await uploadImage(fileEl.files[0]);} let res=row.id?await sb.from(table).update(obj).eq('id',row.id):await sb.from(table).insert(obj); if(res.error) throw res.error; modal.remove();toast('Saved');await loadCollection(table);}catch(err){toast(err.message||'Save failed')}finally{save.disabled=false;}}; }
async function deleteRow(table,id){if(!confirm('Delete this item?'))return;const {error}=await sb.from(table).delete().eq('id',id);if(error)toast(error.message);else{toast('Deleted');loadCollection(table)}}
['services','projects','insights','testimonials'].forEach(t=>$('#new'+t[0].toUpperCase()+t.slice(1,-1)).onclick=()=>editRow(t,{}));
boot();
