const { createClient } = supabase;
const sb = createClient(window.SUPABASE_URL, window.SUPABASE_ANON_KEY);
const $ = selector => document.querySelector(selector);
const $$ = selector => [...document.querySelectorAll(selector)];
const toast = message => { const el = $('#toast'); el.textContent = message; el.style.display = 'block'; setTimeout(() => el.style.display = 'none', 2200); };
const esc = value => String(value ?? '').replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));

async function uploadImage(file) {
  if (!file) throw new Error('Choose an image file before saving.');
  if (typeof file.type !== 'string' || !file.type.toLowerCase().startsWith('image/')) throw new Error('Select a valid image file.');
  if (!Number.isFinite(file.size) || file.size > 5 * 1024 * 1024) throw new Error('Image must be 5 MB or smaller.');
  const types = {'image/jpeg':'jpg','image/png':'png','image/webp':'webp','image/gif':'gif','image/avif':'avif','image/svg+xml':'svg','image/bmp':'bmp'};
  const filename = String(file.name || ''), suffix = filename.includes('.') ? filename.split('.').pop().toLowerCase().replace(/[^a-z0-9]/g, '') : '';
  const extension = types[file.type.toLowerCase()] || suffix || 'img';
  const unique = globalThis.crypto?.randomUUID?.() || `${Date.now().toString(36)}-${Math.random().toString(36).slice(2)}`;
  const path = `projects/${Date.now()}-${unique}.${extension}`, storage = sb.storage.from('portfolio-media');
  const {error} = await storage.upload(path, file, {upsert:false, contentType:file.type});
  if (error) throw new Error(error.message || 'Image upload failed.');
  const {data} = storage.getPublicUrl(path);
  if (!data?.publicUrl) throw new Error('Image uploaded, but Supabase did not return a public URL.');
  return data.publicUrl;
}
async function uploadBrandLogo(file) {
  if (!file) throw new Error('Choose an SVG or PNG logo before saving.');
  const type = String(file.type || '').toLowerCase(), filename = String(file.name || '').toLowerCase();
  const svg = type === 'image/svg+xml' || (!type && filename.endsWith('.svg'));
  const png = type === 'image/png' || (!type && filename.endsWith('.png'));
  if (!svg && !png) throw new Error('Logo must be an SVG or PNG file.');
  if (!Number.isFinite(file.size) || file.size > 2 * 1024 * 1024) throw new Error('Logo must be 2 MB or smaller.');
  const unique = globalThis.crypto?.randomUUID?.() || `${Date.now().toString(36)}-${Math.random().toString(36).slice(2)}`;
  const path = `brands/${Date.now()}-${unique}.${svg ? 'svg' : 'png'}`, storage = sb.storage.from('portfolio-media');
  const {error} = await storage.upload(path, file, {upsert:false, contentType:svg ? 'image/svg+xml' : 'image/png'});
  if (error) throw new Error(error.message || 'Logo upload failed.');
  const {data} = storage.getPublicUrl(path);
  if (!data?.publicUrl) throw new Error('Logo uploaded, but Supabase did not return a public URL.');
  return data.publicUrl;
}
async function boot() { const {data:{session}} = await sb.auth.getSession(); if (session) showApp(); else $('#loginView').classList.remove('hidden'); }
function showApp() { $('#loginView').classList.add('hidden'); $('#app').classList.remove('hidden'); loadAll(); }
$('#loginForm').addEventListener('submit', async event => { event.preventDefault(); $('#loginError').textContent=''; const {error}=await sb.auth.signInWithPassword({email:$('#email').value,password:$('#password').value}); if(error) $('#loginError').textContent=error.message; else showApp(); });
$('#logout').onclick = async () => { await sb.auth.signOut(); location.reload(); };
const pageDescriptions={dashboard:'A clear overview of your portfolio content and publishing tools.',home:'Edit homepage, profile, and contact content.',services:'Manage the service cards shown across your site.',projects:'Organize projects and verified case studies.',trusted_brands:'Manage active logos featured in the homepage marquee.',inquiries:'Review and respond to contact requests.',insights:'Create, edit, and publish marketing insights.',testimonials:'Manage client feedback shown on the portfolio.',settings:'Update contact details, social profiles, and site metadata.'};
function openTab(tab){const button=$(`.side-nav button[data-tab="${tab}"]`);if(!button)return;$$('.side-nav button[data-tab]').forEach(item=>item.classList.remove('active'));button.classList.add('active');$$('.panel').forEach(panel=>panel.classList.remove('active'));$('#'+tab).classList.add('active');$('#pageTitle').textContent=button.textContent.trim();$('#pageDescription').textContent=pageDescriptions[tab]||'';$('#app').classList.remove('sidebar-open');$('#sidebarToggle').setAttribute('aria-expanded','false');}
$$('.side-nav button[data-tab]').forEach(button=>button.onclick=()=>openTab(button.dataset.tab));
$('#sidebarToggle').onclick=()=>{const open=$('#app').classList.toggle('sidebar-open');$('#sidebarToggle').setAttribute('aria-expanded',String(open));$('#sidebarToggle').setAttribute('aria-label',open?'Close navigation':'Open navigation');};
$('#drawerScrim').onclick=()=>{ $('#app').classList.remove('sidebar-open');$('#sidebarToggle').setAttribute('aria-expanded','false');};
$$('[data-open-tab]').forEach(button=>button.onclick=()=>openTab(button.dataset.openTab));
$('#quickAddProject').onclick=()=>$('#newProject').click();$('#quickAddBrand').onclick=()=>$('#newTrustedBrand').click();$('#quickAddInsight').onclick=()=>$('#newInsight').click();$('#quickEditContent').onclick=()=>openTab('home');
async function loadAll() { await Promise.all([loadHome(),loadCollection('services'),loadCollection('projects'),loadCollection('trusted_brands'),loadCollection('insights'),loadCollection('testimonials'),loadInquiries()]); }
async function loadHome() {
  const {data,error}=await sb.from('site_content').select('*').eq('id',1).single(); if(error){$('#status').textContent=error.message;return;}
  fill($('#homeForm'),data); fill($('#settingsForm'),data);
  if (!$('#profileUpload')) { const wrap=document.createElement('div'); wrap.innerHTML='<label>Upload profile image</label><input id="profileUpload" type="file" accept="image/*"><div class="status">Uploading replaces the profile image URL when you save.</div>'; const target=$('#homeForm').querySelector('[name=profile_image_url]')?.parentElement; if(target) target.appendChild(wrap); $('#profileUpload').onchange=async()=>{try{$('#homeForm').elements.profile_image_url.value=await uploadImage($('#profileUpload').files[0]);toast('Image uploaded');}catch(error){toast(error.message);}}; }
}
function fill(form,data){Object.entries(data||{}).forEach(([key,value])=>{const field=form.elements[key];if(field)field.value=value??'';});}
async function saveForm(form){const data={};[...form.elements].forEach(field=>{if(field.name)data[field.name]=field.value;});data.updated_at=new Date().toISOString();const {error}=await sb.from('site_content').update(data).eq('id',1);if(error)throw error;toast('Saved successfully');}
$('#homeForm').onsubmit=async event=>{event.preventDefault();try{await saveForm(event.target);}catch(error){toast(error.message);}};
$('#settingsForm').onsubmit=async event=>{event.preventDefault();try{await saveForm(event.target);}catch(error){toast(error.message);}};
const schemas={
 services:{title:'Service',fields:[['number','Number'],['title','Title'],['description','Description','textarea'],['cta_label','Button label'],['cta_url','Button URL'],['sort_order','Order','number']]},
 projects:{title:'Project',fields:[['category','Category'],['title','Title'],['slug','Slug'],['description','Description','textarea'],['challenge','Challenge','textarea'],['strategy','Strategy','textarea'],['execution','Execution','textarea'],['services_used','Services Used','textarea'],['tools_used','Tools Used','textarea'],['results','Results','textarea'],['image_url','Image URL'],['cta_label','Button label'],['cta_url','Button URL'],['sort_order','Order','number'],['featured','Featured','checkbox']]},
 insights:{title:'Insight',fields:[['category','Category'],['title','Title'],['excerpt','Excerpt','textarea'],['url','Article URL'],['sort_order','Order','number'],['published','Published','checkbox']]},
 testimonials:{title:'Testimonial',fields:[['name','Name'],['role','Role'],['company','Company'],['quote','Quote','textarea'],['avatar_url','Avatar URL'],['sort_order','Order','number'],['published','Published','checkbox']]}
};
async function loadCollection(table){const orderField=table==='trusted_brands'?'display_order':'sort_order';const {data,error}=await sb.from(table).select('*').order(orderField,{ascending:true});if(error){toast(error.message);return;}const rows=data||[];if(table==='trusted_brands'){$('#countTrustedBrands').textContent=rows.filter(row=>row.is_active).length;$('#trustedBrandsList').innerHTML='';rows.forEach(row=>addListItem(table,row));renderDashboardBrands(rows);if(!rows.length)$('#trustedBrandsList').innerHTML='<tr><td colspan="5" class="table-empty">No trusted brands yet. Add a brand to feature its logo.</td></tr>';return;}$('#'+table+'List').innerHTML='';rows.forEach(row=>addListItem(table,row));const counter=table==='insights'?$('#dashboardPublishedInsights'):$('#count'+table[0].toUpperCase()+table.slice(1));if(counter)counter.textContent=table==='insights'?rows.filter(row=>row.published).length:rows.length;if(table==='projects'){renderDashboardProjects(rows);if(!rows.length)$('#projectsList').innerHTML='<div class="empty-state"><strong>No projects yet</strong><p>Add a verified case study to showcase your work.</p><button class="btn primary" type="button" data-empty-add="projects">+ Add project</button></div>';}else if(!rows.length){const labels={services:['No services yet','Add a service to describe your work.'],insights:['No insights yet','Add an article when you are ready to publish.'],testimonials:['No testimonials yet','Published feedback will appear here.']},message=labels[table];if(message)$('#'+table+'List').innerHTML=`<div class="empty-state"><strong>${message[0]}</strong><p>${message[1]}</p><button class="btn primary" type="button" data-empty-add="${table}">+ Add ${table==='testimonials'?'testimonial':table.slice(0,-1)}</button></div>`;}const addButtons={services:'Service',projects:'Project',insights:'Insight',testimonials:'Testimonial'};$$('[data-empty-add]').forEach(button=>button.onclick=()=>$('#new'+addButtons[button.dataset.emptyAdd])?.click());}
function renderDashboardProjects(rows){const body=$('#dashboardProjects');if(!body)return;if(!rows.length){body.innerHTML='<tr><td colspan="4" class="table-empty"><strong>No projects yet</strong><br>Add your first case study from Quick Actions.</td></tr>';return;}const recent=[...rows].sort((a,b)=>new Date(b.updated_at||b.created_at||0)-new Date(a.updated_at||a.created_at||0)).slice(0,5);body.innerHTML=recent.map(row=>{const updated=row.updated_at||row.created_at,date=updated&&!Number.isNaN(Date.parse(updated))?new Intl.DateTimeFormat(undefined,{month:'short',day:'numeric',year:'numeric'}).format(new Date(updated)):'—';return `<tr><td><span class="recent-project-name">${esc(row.title||'Untitled project')}</span><span class="recent-project-category">${esc(row.category||'')}</span></td><td>${row.featured?'<span class="status-badge featured">Featured</span>':'<span class="status-badge inactive">Not featured</span>'}</td><td>${esc(date)}</td><td><button class="btn table-action" type="button" data-dashboard-edit="${esc(row.id)}">Edit</button></td></tr>`;}).join('');body.querySelectorAll('[data-dashboard-edit]').forEach(button=>button.onclick=()=>{const project=rows.find(row=>String(row.id)===button.dataset.dashboardEdit);if(project)editRow('projects',project);});}
function renderDashboardBrands(rows){const active=rows.filter(row=>row.is_active&&row.logo_url);$('#dashboardBrandCount').textContent=active.length;const preview=$('#dashboardBrandPreview');preview.innerHTML=active.slice(0,5).map(row=>`<img src="${esc(row.logo_url)}" alt="${esc(row.name)}" loading="lazy">`).join('');}
async function loadInquiries(){const body=$('#inquiriesList'),counter=$('#countNewInquiries');try{const {data,error}=await sb.from('contact_inquiries').select('*').order('created_at',{ascending:false});if(error)throw error;const rows=data||[];counter.textContent=rows.filter(row=>row.status==='new').length;renderInquiries(rows);}catch(error){counter.textContent='—';body.innerHTML='<tr><td colspan="8" class="table-empty">Inquiries are unavailable. Apply the contact inquiries Supabase migration to enable this view.</td></tr>';}}
function renderInquiries(rows){const body=$('#inquiriesList');if(!rows.length){body.innerHTML='<tr><td colspan="8" class="table-empty">No inquiries received yet.</td></tr>';return;}body.innerHTML=rows.map(row=>{const stamp=row.created_at&&Date.parse(row.created_at),date=stamp?new Intl.DateTimeFormat(undefined,{month:'short',day:'numeric',year:'numeric'}).format(new Date(stamp)):'—';return `<tr><td><strong>${esc(row.name)}</strong></td><td><a href="mailto:${esc(row.email)}">${esc(row.email)}</a></td><td>${esc(row.company||'—')}</td><td>${esc(row.service)}</td><td><span class="inquiry-message-preview" title="${esc(row.message)}">${esc(row.message)}</span></td><td><span class="status-badge inquiry-status ${esc(row.status)}">${esc(row.status)}</span></td><td>${esc(date)}</td><td><button class="btn table-action" type="button" data-view-inquiry="${esc(row.id)}">View / Edit</button></td></tr>`;}).join('');body.querySelectorAll('[data-view-inquiry]').forEach(button=>button.onclick=()=>{const row=rows.find(item=>String(item.id)===button.dataset.viewInquiry);if(row)openInquiry(row);});}
function openInquiry(row){const modal=document.createElement('div'),stamp=row.created_at&&Date.parse(row.created_at),submitted=stamp?new Intl.DateTimeFormat(undefined,{dateStyle:'medium',timeStyle:'short'}).format(new Date(stamp)):'—';modal.className='modal-overlay';modal.innerHTML=`<section class="admin-modal modal-form" role="dialog" aria-modal="true" aria-labelledby="inquiryDialogTitle"><h2 id="inquiryDialogTitle">Contact inquiry</h2><dl class="inquiry-details"><div><dt>Name</dt><dd>${esc(row.name)}</dd></div><div><dt>Email</dt><dd><a href="mailto:${esc(row.email)}">${esc(row.email)}</a></dd></div><div><dt>Company / Brand</dt><dd>${esc(row.company||'—')}</dd></div><div><dt>Service</dt><dd>${esc(row.service)}</dd></div><div><dt>Submitted</dt><dd>${esc(submitted)}</dd></div><div><dt>Status</dt><dd><select name="status" aria-label="Inquiry status"><option value="new" ${row.status==='new'?'selected':''}>New</option><option value="contacted" ${row.status==='contacted'?'selected':''}>Contacted</option><option value="closed" ${row.status==='closed'?'selected':''}>Closed</option></select></dd></div><div class="full"><dt>Project message</dt><dd class="inquiry-message">${esc(row.message)}</dd></div></dl><div class="row modal-footer"><button class="btn danger" type="button" data-delete-inquiry>Delete</button><button class="btn" type="button" data-close>Close</button><button class="btn primary" type="button" data-save-status>Save status</button></div></section>`;document.body.appendChild(modal);modal.querySelector('[data-close]').onclick=()=>modal.remove();modal.querySelector('[data-save-status]').onclick=async()=>{const save=modal.querySelector('[data-save-status]');save.disabled=true;try{const {error}=await sb.from('contact_inquiries').update({status:modal.querySelector('[name="status"]').value}).eq('id',row.id);if(error)throw error;modal.remove();toast('Inquiry status updated');await loadInquiries();}catch(error){toast('Could not update inquiry status.');}finally{save.disabled=false;}};modal.querySelector('[data-delete-inquiry]').onclick=async()=>{if(!confirm('Delete this inquiry? This cannot be undone.'))return;try{const {error}=await sb.from('contact_inquiries').delete().eq('id',row.id);if(error)throw error;modal.remove();toast('Inquiry deleted');await loadInquiries();}catch(error){toast('Could not delete inquiry.');}};}
function addListItem(table,row){if(table==='trusted_brands'){const tr=document.createElement('tr');tr.innerHTML=`<td><strong>${esc(row.name)}</strong></td><td><img src="${esc(row.logo_url)}" alt="${esc(row.name)} logo" loading="lazy" class="admin-logo-preview"></td><td>${esc(row.display_order??0)}</td><td><span class="status-badge ${row.is_active?'published':'inactive'}">${row.is_active?'Active':'Inactive'}</span></td><td><button class="btn" data-edit>Edit</button> <button class="btn danger" data-delete>Delete</button></td>`;tr.querySelector('[data-edit]').onclick=()=>editTrustedBrand(row);tr.querySelector('[data-delete]').onclick=()=>deleteRow(table,row.id);$('#trustedBrandsList').appendChild(tr);return;}const status=row.published!==undefined?`<span class="status-badge ${row.published?'published':'draft'}">${row.published?'Published':'Draft'}</span>`:table==='projects'&&row.featured?'<span class="status-badge featured">Featured</span>':'';const item=document.createElement('div');item.className='item';item.innerHTML=`<div><strong>${esc(row.title||row.name||'Untitled')}</strong><small>${esc(row.category||row.role||'')}</small></div><div class="item-actions">${status}<button class="btn" data-edit>Edit</button> <button class="btn danger" data-delete>Delete</button></div>`;item.querySelector('[data-edit]').onclick=()=>editRow(table,row);item.querySelector('[data-delete]').onclick=()=>deleteRow(table,row.id);$('#'+table+'List').appendChild(item);}
function editRow(table,row){const schema=schemas[table],imageFields=['image_url','avatar_url'];const html=schema.fields.map(([key,label,type])=>{const isImage=imageFields.includes(key);return `<div class="${['description','quote','services_used','results','challenge','strategy','execution','tools_used'].includes(key)?'full':''}"><label>${label}</label>${type==='textarea'?`<textarea name="${key}">${esc(row[key]||'')}</textarea>`:type==='checkbox'?`<input type="checkbox" name="${key}" ${row[key]?'checked':''}>`:type==='number'?`<input type="number" name="${key}" value="${row[key]??0}">`:`<input name="${key}" value="${esc(row[key]||'')}" ${isImage?'data-image-url':''}>${isImage?`<div style="margin-top:8px"><input type="file" accept="image/*" data-image-file="${key}"><small style="color:#657985">Upload image or paste a URL above.</small></div>`:''}`}</div>`;}).join('');const modal=document.createElement('div');modal.className='modal-overlay';modal.innerHTML=`<div class="admin-modal modal-form" role="dialog" aria-modal="true"><h2>${row.id?'Edit':'Add'} ${schema.title}</h2><form class="grid">${html}</form><div class="row modal-footer"><button class="btn" type="button" data-close>Cancel</button><button class="btn primary" type="button" data-save>Save</button></div></div>`;document.body.appendChild(modal);modal.querySelector('[data-close]').onclick=()=>modal.remove();modal.querySelector('[data-save]').onclick=async()=>{const save=modal.querySelector('[data-save]');save.disabled=true;try{const obj={};[...modal.querySelector('form').elements].forEach(field=>{if(field.name)obj[field.name]=field.type==='checkbox'?field.checked:field.value;});if(table==='projects'&&obj.slug){if(!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(obj.slug))throw new Error('Use a lowercase slug with letters, numbers, and single hyphens.');const {data:slugs,error}=await sb.from('projects').select('id').eq('slug',obj.slug);if(error)throw error;if(slugs.some(item=>item.id!==row.id))throw new Error('That slug is already in use. Choose a unique slug.');}for(const key of imageFields){const file=modal.querySelector(`[data-image-file="${key}"]`)?.files?.[0];if(file)obj[key]=await uploadImage(file);}const result=row.id?await sb.from(table).update(obj).eq('id',row.id):await sb.from(table).insert(obj);if(result.error)throw result.error;modal.remove();toast('Saved');await loadCollection(table);}catch(error){toast(error.message||'Save failed');}finally{save.disabled=false;}};}
function editTrustedBrand(row={}){const brand={display_order:0,is_active:true,grayscale:true,...row};const modal=document.createElement('div');modal.className='modal-overlay';modal.innerHTML=`<div class="admin-modal modal-form" role="dialog" aria-modal="true"><h2>${brand.id?'Edit':'Add'} Trusted Brand</h2><form class="grid"><div class="full"><label>Brand Name</label><input name="name" required value="${esc(brand.name||'')}"></div><div class="full"><label>Logo URL</label><input name="logo_url" required value="${esc(brand.logo_url||'')}"><div style="margin-top:10px"><input type="file" accept=".svg,.png,image/svg+xml,image/png" data-brand-logo><small class="status">Recommended: SVG or transparent PNG • 800×300px • Maximum 2MB</small></div></div><div class="full"><label>Website URL</label><input name="website_url" type="url" value="${esc(brand.website_url||'')}"></div><div><label>Display Order</label><input name="display_order" type="number" value="${esc(brand.display_order)}"></div><div><label><input type="checkbox" name="is_active" ${brand.is_active?'checked':''}> Active</label></div><div><label><input type="checkbox" name="grayscale" ${brand.grayscale?'checked':''}> Grayscale by default</label></div></form><div class="row modal-footer"><button class="btn" type="button" data-close>Cancel</button><button class="btn primary" type="button" data-save>Save Brand</button></div></div>`;document.body.appendChild(modal);modal.querySelector('[data-close]').onclick=()=>modal.remove();modal.querySelector('[data-save]').onclick=async()=>{const save=modal.querySelector('[data-save]');save.disabled=true;try{const form=modal.querySelector('form'),obj={};[...form.elements].forEach(field=>{if(field.name)obj[field.name]=field.type==='checkbox'?field.checked:field.value;});obj.display_order=Number(obj.display_order)||0;obj.updated_at=new Date().toISOString();const file=modal.querySelector('[data-brand-logo]').files[0];if(file)obj.logo_url=await uploadBrandLogo(file);if(!obj.name.trim())throw new Error('Enter a brand name.');if(!obj.logo_url.trim())throw new Error('Enter a logo URL or upload a logo.');const result=brand.id?await sb.from('trusted_brands').update(obj).eq('id',brand.id):await sb.from('trusted_brands').insert(obj);if(result.error)throw result.error;modal.remove();toast('Brand saved');await loadCollection('trusted_brands');}catch(error){toast(error.message||'Save failed.');}finally{save.disabled=false;}};}
async function deleteRow(table,id){if(!confirm('Delete this item?'))return;const {error}=await sb.from(table).delete().eq('id',id);if(error)toast(error.message);else{toast('Deleted');loadCollection(table);}}
['services','projects','insights','testimonials'].forEach(table=>$('#new'+table[0].toUpperCase()+table.slice(1,-1)).onclick=()=>editRow(table,{}));
$('#newTrustedBrand').onclick=()=>editTrustedBrand();
boot();
